# openai api key
# you can get it here: https://platform.openai.com/account/api-keys
key = "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"

# proxy url. if it's not empty, 
# backend will connect the OpenAI API through it
# proxy = "http://127.0.0.1:1080"
proxy = "http://127.0.0.1:7890"

# backend url and port
host = ":8081"

# backend api path
api = "/chat"

# serve frontend's static files from "dist" folder
# if false, backend will only serve as a remote api
serve_static = true
